### ISSUE TITLE
Redesign Values

### ISSUE THREAD

**Issue by witling** [lausek/lovm2#4]
**Problems:**
- Two different modules (`co_value` and `ru_value`) with basically the same operations defined on them
- No way of mutating a Value other than `Dict` and `List` in place/by reference. This makes the implementation of python like slices more difficult.

**Steps for redesign:**
- Rename `CoValue -> Value`
- `RuValue` contains either a `Value` or a `Ref(Rc<RefCell<Value>>)`
- Add a new instruction `Box` for turning the top of stack into a `Ref`
- *needed?* Add a new instruction `Unbox` for turning the top of stack into a `Value` (basically a clone)

**Pros:**
- Operations like `Add` are defined for compile time values as well
- Cleanup of codebase

**Cons:**
- Indirection checks are now required when working with `RuValue`

**Comment by witling** [comment]
**Different idea:**

Create a new variant on Value containing an Option.

```rust
enum Value {
    Nil,
    Bool(bool),
    Int(i64),
    ...
    Ref(Option<Rc<RefCell<Value>>),
}
```

**Pros:**
- No additional indirections when working with values on the stack
- Serializeable by setting each reference to `Value::Ref(None)`

**Comment by witling** [comment]
**Problem:** How do we overwrite values inside `Value::Ref(_)`?

**Ideas:**
- Add a `Move` Instruction that takes the first value as location and the second one as value

**Comment by witling** [comment]
**Problem:** What if we `set` a non-reference onto a `List`?

These two examples should essentially do the same with the predefined list `MyList([Value::Ref(None), Value::Ref(None)])`

writing ex. 1:
```
pushl 0 ; MyList
pushc 0 ; index 1
get
pushc 2
move
```

writing ex. 2:
```
pushl 0 ; MyList
pushc 0 ; index 1
pushc 2
set
```

**Idea:**
- Add a configuration variable `autobox_nested_values` to the LoweringRuntime that is active by default. It basically adds a `Box` instruction each time we are trying to set a `Dict` or `List` field.

**Comment by lausek** [comment]
The best decision would be to change the meaning of `Get` and `Set` rather than implementing a new Instruction `Move`.
- `Get` takes two values - a target and a key - and returns a `Ref` to the value on stack
- `Set` takes two parameters from stack - a reference and a value. It handles dereferencing and updating the slot in-place.

This should not break the current behavior of list and dictionary mutation.

**Sidenote:** please make `Get` and `Set` real HIR elements. Treating them as functions is confusing.

**Comment by lausek** [comment]
`Box(u16)` Instruction
- takes the index of a constant value as argument
    - if the value is indexable, traverse all components and box them too. this makes sure that we can reference every slot in a list or dictionary.
- leaves a `Ref` to the boxed value on stack 

`Unbox` takes the last value from stack and pushes the inner value. *needed?*

**Comment by lausek** [comment]
transition was done in c76fc74.

- creating a list or dict automatically creates a reference around itself and each value contained. `value.set` ensures that new values are wrapped up as well.
- new instruction `Getr` for gettig a reference of a value inside list or dict
- `Set` now expects two references on the stack
- no `Unbox` instruction needed
